[package]
name = "rust-ants-book"
version = "0.1.0"
authors = ["kazukiyoshida"]
edition = "2018"

[[bin]]
name = "main1"
path = "src/main1.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"

[dependencies]
